# Site settings
title: Edouard COMTET - Software engineer
email: edouard.comtet@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Passioné d'informatique!
  Ingénieur full stack.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ecomtet.com/" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: 'Edouard COMTET'
  email: edouard.comtet@gmail.com
  cv: true
  gitlab_username:  DarkIsDude
  twitter_username: DarkIsDude
  medium_username: darkIsDude
  github_username:  DarkIsDude
  linkedin_username:  comtet-edouard-87b84870

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
include: ['_pages']
